### ISSUE TITLE
Documentation path Linux

### ISSUE THREAD

**Issue by edwardpmorris** [mattocci27/LeafArea#1]
For Linux, where for example ImageJ standalone is in a directory `~/ImageJ`, when specifying the ImageJ path in `run_ij` the documentation gives the impression `path.imagej` should be `~/ImageJ`, but the function `run_ij` appends `ImageJ` to the path, giving error `Specify the correct path to ImageJ`. 

Maybe could make it clear in the documentation "path to directory *containing* ImageJ directory" or adjust the `run_ij` function:

```
unix.check <- Sys.info()["sysname"]
  if (unix.check == "Linux") {
    if (file.exists(paste(path.imagej, "ij.jar", 
                          sep = "")) != T & file.exists(paste(path.imagej, "ij.jar", sep = "/")) != T) {
      warning("Specify the correct path to ImageJ")
      return("ImageJ not found")
    }
  }
```

**Comment by mattocci27** [comment]
Thank you for reporting. Now Linux users need to specify the path to directory that contains ImageJ.app and ij.jr. I have changed the warning as well.  

The fixed version is available here but not in CRAN yet..
devtools::install_github("mattocci27/LeafArea")
