### ISSUE TITLE
Unable to find Java in updated ImageJ

### ISSUE THREAD

**Issue by hrdawson** [mattocci27/LeafArea#3]
Dear Dr. Katabuchi,

I've found a small bug caused by a change in filepath in the most recent ImageJ. After receiving the "ImageJ not found" error, I discovered that more accurately, Java isn't found. Your code locates Java in "Contents/Resources/Java/ij.jar"; however, it now resides in "Contents/Java/ij.jar". My work around is to move the Java file into Resources which allows the code to run, although it still displays a hefty error message at the end:
`Warning messages:
1: In if (imagej == "ImageJ not found") return("ImageJ not found") else path.imagej <- imagej :
  the condition has length > 1 and only the first element will be used
2: In if (file.exists(paste(path.imagej, "Contents/Resources/Java/ij.jar",  :
  the condition has length > 1 and only the first element will be used
3: In if (temp.slash2 != "/") { :
  the condition has length > 1 and only the first element will be used`

Thank you for writing and maintaining this code.

Best,
Hilary Rose Dawson

**Comment by mattocci27** [comment]
Hi, thank you for reporting. It's updated in the [dev version](https://github.com/mattocci27/LeafArea/tree/dev) but not for the CARN version yet. I will upload it to CRAN soon.
