### ISSUE TITLE
results error

### ISSUE THREAD

**Issue by lixiang117423** [mattocci27/LeafArea#4]
Dear Mr. Masatoshi Katabuchi,
I am using your package to analyze the area of six rice leaves in a figure.
The result generated by your package is 97.389, but the results from ImageJ by manual analysis is 1076.088.
So I do not keno which one is right.
This is the code I used in the analysis.
```
res <- run.ij(path.imagej = 'E:/ImageJ/ImageJ',
              set.directory = 'C:/Users/Administrator/Desktop/test/')
```
Any reply is appreciated.
Thank you!

**Comment by mattocci27** [comment]
Please check `distance.pixel` and `known.distance` in the `run.ij` function. The default values are `distance.pixel = 826` and `known.distance = 21`. So, in default, `run.ij` recognizes 826 pixels = 21 cm in your images.
