### ISSUE TITLE
run.ij returning area but not perimeter

### ISSUE THREAD

**Issue by alibabington** [mattocci27/LeafArea#5]
Hi there, 

I have been using the run.ij command as follows:

run.ij(path.imagej = NULL, set.memory = 4, set.directory,
       distance.pixel = 2475.6, known.distance = 21, trim.pixel = 20,
       low.circ = 0, upper.circ = 1, low.size = 0.1,
       upper.size = "Infinity", prefix = "\\.|-", log = F,
       check.image = F, save.image = F)

The area function is working well and returns this:
> run.ij(path.imagej = NULL, set.memory = 4, set.directory,
+        distance.pixel = 2475.6, known.distance = 21, trim.pixel = 20,
+        low.circ = 0, upper.circ = 1, low.size = 0.1,
+        upper.size = "Infinity", prefix = "\\.|-", log = F,
+        check.image = F, save.image = F)
 	Area	Mean	Min	Max	XStart	YStart
1	2.074	116.245	63	173	698	875
 	Area	Mean	Min	Max	XStart	YStart
1	19.907	117.479	54	180	956	481
 	Area	Mean	Min	Max	XStart	YStart
1	35.014	114.129	52	177	1364	706
 	Area	Mean	Min	Max	XStart	YStart
1	19.921	117.326	59	180	1226	264
2	34.971	111.526	58	180	442	859
3	2.095	114.944	62	180	1309	1287
4	1.012	112.259	60	180	1037	1798
 	Area	Mean	Min	Max	XStart	YStart
1	1.009	113.158	59	171	718	970
  sample total.leaf.area
1   Scan           1.009
2 Scan 1           2.074
3 Scan 2          19.907
4 Scan 3          35.014
5 Scan 5          57.999

** These are scans from pieces of paper of known size to check 

How do I add the perimeter to this as well? I had a look at the 'adding perim' section but I'm confused sorry. 
Cheers

**Comment by mattocci27** [comment]
Sorry, I removed the option to calculate perimeter at some point, but the README was not updated. I made another version that can record perimeter. Please copy and paste the following command on your R console. 

```{r}
devtools::install_github("mattocci27/LeafArea@peri")
```
This will install the new version. Please let me know if the estimate is wrong.

**Comment by alibabington** [comment]
Hi Masatoshi, 

It worked - thank you so much! I really appreciate it and you have made my next couple of weeks so much easier. 

Cheers, 
Ali
